/**
 * All user-facing text (Indonesian). Keep strings here, never inside components.
 * Grouped by area so a future i18n layer can replace this file.
 */
export const copy = {
  common: {
    save: 'Simpan',
    saving: 'Menyimpan…',
    saved: 'Tersimpan',
    unsaved: 'Belum disimpan',
    cancel: 'Batal',
    delete: 'Hapus',
    edit: 'Edit',
    add: 'Tambah',
    search: 'Cari',
    loading: 'Memuat…',
    back: 'Kembali',
    copyLink: 'Salin tautan',
    copied: 'Berhasil disalin',
    preview: 'Pratinjau',
    publish: 'Publikasikan',
    unpublish: 'Batalkan publikasi',
    genericError: 'Terjadi kesalahan. Silakan coba lagi.',
    optional: 'opsional',
    all: 'Semua',
    close: 'Tutup',
    view: 'Lihat',
  },
  admin: {
    openMenu: 'Buka menu',
    closeMenu: 'Tutup menu',
    expandMenu: 'Bentangkan menu',
    collapseMenu: 'Ciutkan menu',
    panelSubtitle: 'Panel Admin',
  },
  dashboard: {
    subtitle: 'Ringkasan bisnis undangan digital Anda.',
    stats: {
      customers: 'Pelanggan',
      invitations: 'Undangan',
      published: 'Undangan terbit',
      rsvps: 'Total RSVP',
      guests: 'Tamu hadir',
      messages: 'Ucapan',
      views: 'Dilihat',
    },
    recent: 'Undangan terbaru',
    viewAll: 'Lihat semua',
    updatedAt: 'Diperbarui',
    analyticsLink: 'Lihat grafik views dan RSVP per hari →',
  },
  analytics: {
    rangeTitle: '14 hari terakhir',
    chartLabel: 'Grafik dilihat dan RSVP',
    chartLabelOne: 'Grafik dilihat dan RSVP undangan ini',
    viewsDays: 'Dilihat (14 hari)',
    seen: 'Dilihat',
    rsvpSeries: 'RSVP',
  },
  auth: {
    title: 'Masuk ke panel admin',
    subtitle: 'Kelola pelanggan dan undangan Anda.',
    email: 'Email',
    password: 'Kata sandi',
    submit: 'Masuk',
    invalid: 'Email atau kata sandi salah.',
    notAdmin: 'Akun ini tidak memiliki akses admin.',
    logout: 'Keluar',
    mockHint: 'Mode demo: gunakan admin@talijiwa.id / admin123',
  },
  nav: {
    dashboard: 'Dashboard',
    customers: 'Pelanggan',
    orders: 'Pesanan',
    invitations: 'Undangan',
    themes: 'Tema',
    analytics: 'Analitik',
    settings: 'Pengaturan',
    menuAdmin: 'Menu admin',
  },
  invitations: {
    unit: 'undangan',
    searchPh: 'Cari pasangan, slug, atau pelanggan',
    searchAria: 'Cari undangan',
    filterAria: 'Filter status',
    statuses: { all: 'Semua', draft: 'Draf', published: 'Terbit', archived: 'Arsip' },
    noMatch: 'Tidak ada undangan yang cocok.',
    cannotPublish: 'Belum bisa dipublikasikan:',
    duplicated: 'Undangan diduplikasi',
    deleted: 'Undangan dihapus',
    archived: 'Undangan diarsipkan',
    backToDraft: 'Dikembalikan ke draf',
    copyAria: 'Salin tautan',
    moreActions: 'Aksi lainnya',
    duplicate: 'Duplikasi',
    archive: 'Arsipkan',
    restoreDraft: 'Kembalikan ke draf',
    editAria: 'Edit',
    deleteTitle: 'Hapus undangan?',
    deleteMsg: 'beserta RSVP, ucapan, dan konfirmasi hadiahnya akan dihapus permanen.',
    orderPrefix: 'Pesanan:',
    publishErrTitle: 'Judul dan slug belum diisi.',
    publishErrCouple: 'Nama mempelai belum lengkap.',
    publishErrEvents: 'Belum ada acara lengkap (tanggal dan tempat).',
    publishErrMusic: 'Tautan musik belum diisi.',
  },
  customers: {
    saved: 'Pelanggan disimpan',
    deleted: 'Pelanggan dihapus',
    add: 'Tambah pelanggan',
    edit: 'Edit pelanggan',
    searchPh: 'Cari nama, telepon, atau email',
    searchAria: 'Cari pelanggan',
    noMatch: 'Tidak ada pelanggan yang cocok dengan',
    noContact: 'Tanpa kontak',
    invitationUnit: 'undangan',
    deleteTitle: 'Hapus pelanggan?',
    deleteMsg: 'akan dihapus permanen. Pelanggan yang masih punya undangan tidak bisa dihapus.',
    formName: 'Nama',
    formNameError: 'Nama wajib diisi.',
    formPhone: 'Telepon / WhatsApp',
    formEmail: 'Email',
    formEmailError: 'Format email tidak valid.',
    formNotes: 'Catatan',
    detailBack: 'Pelanggan',
    detailMissing: 'Pelanggan tidak ditemukan.',
    detailSince: 'Terdaftar',
    detailOrders: 'Pesanan',
    detailManageOrders: 'Kelola pesanan',
    detailInvitations: 'Undangan',
    detailNoInvitations: 'Pelanggan ini belum punya undangan.',
    detailNoDate: 'Tanggal belum diisi',
    detailPhone: 'Telepon',
    detailEmail: 'Email',
    detailNotes: 'Catatan',
    detailEmpty: '—',
  },
  invitation: {
    notFound: 'Undangan tidak ditemukan',
    notPublished: 'Undangan belum dipublikasikan',
    unavailable: 'Undangan ini sudah tidak tersedia',
    weddingOf: 'THE WEDDING OF',
    dear: 'Kepada Yth.',
    defaultGuest: 'Bapak/Ibu/Saudara/i',
    open: 'Buka Undangan',
    todayIsTheDay: 'Hari Bahagia Telah Tiba',
    days: 'Hari',
    hours: 'Jam',
    minutes: 'Menit',
    seconds: 'Detik',
    copyNumber: 'Salin Nomor',
    copied: 'Berhasil disalin',
    openMaps: 'Buka Peta',
  },
  builder: {
    sections: {
      basic: 'Info dasar',
      couple: 'Mempelai',
      story: 'Kisah cinta',
      events: 'Acara',
      gallery: 'Galeri',
      rsvp: 'RSVP',
      messages: 'Ucapan',
      gift: 'Amplop digital',
      music: 'Musik',
      theme: 'Tema & gaya',
      seo: 'SEO',
      publish: 'Publikasi',
      share: 'Bagikan',
    },
    unsavedWarning: 'Perubahan belum disimpan. Yakin ingin meninggalkan halaman ini?',
    tabEdit: 'Edit',
    tabPreview: 'Pratinjau',
    quickOpenFull: 'Buka form lengkap',
    quickEmpty: 'Bagian ini paling enak dilengkapi di form penuh.',
    sectionsMenu: 'Pindah bagian',
    tapHint: 'Ketuk bagian mana pun untuk mengedit.',
    toolbar: 'Bilah alat',
    edit: {
      backToList: 'Kembali ke daftar undangan',
      viewTabs: 'Tampilan',
      undo: 'Urungkan',
      undoTitle: 'Urungkan (Ctrl+Z)',
      redo: 'Ulangi',
      redoTitle: 'Ulangi (Ctrl+Shift+Z)',
      replay: 'Putar ulang',
      replayTitle: 'Putar ulang animasi pratinjau',
      moreActions: 'Aksi lainnya',
      completeFirst: 'Lengkapi data wajib terlebih dahulu',
      nextStep: 'Langkah berikutnya:',
      reload: 'Sembuhkan',
      reloadTitle: 'Muat ulang halaman ini (kosongkan jika kosong)',
      completeAction: 'lengkapi',
      shortcuts: 'Pintasan: Ctrl+S simpan · Ctrl+Z urungkan · Ctrl+Shift+Z ulangi · Alt+←/→ pindah bagian',
      phone: 'Ponsel',
      tablet: 'Tablet',
      try: 'Uji',
      tryHint: 'Coba interaksi asli (tautan, galeri, musik). Matikan untuk kembali mengedit.',
      tryActive: 'Mode uji aktif — klik untuk kembali mengedit.',
      previewSize: 'Ukuran pratinjau',
      clickHint: 'Klik bagian mana pun di pratinjau untuk langsung mengeditnya.',
      formRegion: 'Formulir bagian aktif',
      previewRegion: 'Pratinjau langsung',
      guestSample: 'Nama Tamu',
      downloadQr: 'Unduh QR',
      downloadQrTitle: 'Unduh QR kode undangan',
      downloadedQr: 'QR undangan tersimpan',
      shortUrl: 'Tautan pendek',
    },
    sidebarNav: 'Bagian builder',
    groups: { dasar: 'Dasar', acara: 'Acara & media', tamu: 'Interaksi tamu', tampil: 'Tampilan', rilis: 'Rilis' },
    progressDone: 'lengkap',
    completeness: 'Kelengkapan undangan',
    saveFailed: 'Gagal menyimpan',
    slugChecking: 'Memeriksa ketersediaan…',
    slugOk: 'Slug tersedia.',
    slugTaken: 'Slug sudah dipakai undangan lain.',
    slugInvalid: 'Gunakan huruf kecil, angka, dan tanda hubung (minimal 3 karakter, bukan kata yang dicadangkan).',
    saveSlugTaken: 'Slug sudah dipakai undangan lain.',
    saveSlugInvalid: 'Slug belum valid.',
    issues: {
      title: 'Judul undangan belum diisi.',
      slug: 'Slug belum valid atau sudah dipakai.',
      couple: 'Nama mempelai pria dan wanita wajib diisi.',
      events: 'Tambahkan minimal satu acara lengkap dengan tanggal dan tempat.',
      photos: 'Foto mempelai belum lengkap.',
      gallery: 'Galeri masih kosong. Foto cover memakai gambar bawaan.',
      music: 'Musik diaktifkan tetapi tautan belum diisi.',
    },
    basic: {
      desc: 'Judul, alamat undangan, dan teks sambutan.',
      titleLabel: 'Judul undangan',
      titleHint: 'Biasanya nama panggilan pasangan, mis. Raka & Sinta.',
      titlePh: 'Raka & Sinta',
      slugLabel: 'Alamat undangan (slug)',
      followTitle: 'Ikuti judul',
      greeting: 'Salam pembuka',
      opening: 'Teks pembuka',
      closing: 'Teks penutup',
    },
    couple: {
      desc: 'Data kedua mempelai dan orang tua.',
      groom: 'Mempelai pria',
      bride: 'Mempelai wanita',
      fatherOf: 'Nama ayah mempelai pria',
      fatherOfBride: 'Nama ayah mempelai wanita',
      motherOf: 'Nama ibu mempelai pria',
      motherOfBride: 'Nama ibu mempelai wanita',
      photo: 'Foto',
      fullName: 'Nama lengkap',
      nickname: 'Nama panggilan',
      instagram: 'Instagram',
      father: 'Ayah',
      mother: 'Ibu',
    },
    story: {
      desc: 'Tampil sebagai timeline, diurutkan otomatis berdasarkan tanggal.',
      add: 'Tambah kisah',
      presets: ['Pertemuan Pertama', 'Lamaran', 'Hari Pernikahan'],
      untitled: 'Kisah baru',
      title: 'Judul',
      titlePh: 'Pertemuan Pertama',
      date: 'Tanggal',
      story: 'Cerita',
      photoOpt: 'Foto (opsional)',
      remove: 'Hapus kisah',
    },
    events: {
      desc: 'Tanggal acara paling awal dipakai untuk hitung mundur.',
      akad: 'Akad Nikah',
      resepsi: 'Resepsi',
      other: 'Acara lain',
      untitled: 'Acara',
      name: 'Nama acara',
      namePh: 'Akad Nikah',
      date: 'Tanggal',
      start: 'Mulai',
      end: 'Selesai',
      venue: 'Nama tempat',
      venuePh: 'Gedung Graha Bakti',
      address: 'Alamat',
      maps: 'Tautan Google Maps',
      mapsHint: 'Tempel tautan dari tombol Bagikan di Google Maps.',
      moveUp: 'Naikkan acara',
      moveDown: 'Turunkan acara',
      remove: 'Hapus acara',
    },
    gallery: {
      desc: 'Foto bintang menjadi cover undangan. Gambar dikompres otomatis sebelum disimpan.',
      upload: 'Unggah foto',
      uploadFailed: 'Gagal mengunggah gambar.',
      apply: 'Terapkan',
      tooMany: 'Maksimal {max} foto. Sebagian file dilewati.',
      failed: 'Gagal memproses gambar.',
      counter: 'foto. Seret untuk mengurutkan, bintang untuk cover.',
      cover: 'Cover',
      moveLeft: 'Geser ke kiri',
      moveRight: 'Geser ke kanan',
      crop: 'Potong foto',
      setCover: 'Jadikan cover',
      removePhoto: 'Hapus foto',
      cropTitle: 'Potong foto',
      cropHint: 'Seret foto untuk menggeser posisi. Hasil dipotong sesuai bingkai di atas.',
      cropArea: 'Area potong. Seret atau gunakan tombol panah untuk menggeser, + dan - untuk zoom.',
      zoom: 'Zoom',
      photoAlt: 'Foto',
      recrop: 'Potong ulang',
      removeImage: 'Hapus',
      dropHint: 'Klik atau seret foto ke sini',
      badType: 'Format gambar harus JPG, PNG, atau WebP.',
      tooBig: 'Ukuran gambar maksimal {max} MB.',
      noCanvas: 'Browser tidak mendukung pemrosesan gambar.',
    },
    rsvp: {
      desc: 'Tamu mengisi nama, WhatsApp, jumlah, dan kehadiran.',
      show: 'Tampilkan form RSVP',
      showOff: 'Matikan jika tidak perlu konfirmasi kehadiran.',
      deadline: 'Batas konfirmasi',
      deadlineHint: 'Ditampilkan di atas form RSVP.',
      viewData: 'Lihat data RSVP',
    },
    messages: {
      desc: 'Ucapan tamu tampil di undangan dan bisa dimoderasi.',
      show: 'Tampilkan ucapan & doa',
      showHint: 'Form dan daftar ucapan muncul di undangan.',
      manage: 'Kelola ucapan tamu',
    },
    gift: {
      desc: 'Rekening bank dan e-wallet untuk amplop digital.',
      show: 'Tampilkan amplop digital',
      bank: 'Rekening bank',
      wallet: 'E-wallet',
      removeAccount: 'Hapus rekening',
      bankName: 'Nama bank',
      bankNamePh: 'BCA',
      walletName: 'Nama e-wallet',
      walletNamePh: 'GoPay',
      accountNumber: 'Nomor rekening',
      walletNumber: 'Nomor e-wallet',
      holder: 'Atas nama',
      addBank: 'Tambah rekening',
      addWallet: 'Tambah e-wallet',
      viewConfirmations: 'Lihat konfirmasi hadiah',
    },
    theme: {
      desc: 'Pilih tema, atur teks dan warna, lalu atur urutan bagian undangan.',
      themeSelector: 'Pilih tema',
      fontTheme: 'Ikuti tema',
      fonts: { serif: 'Serif elegan', classic: 'Klasik', script: 'Tulisan tangan', modern: 'Modern' },
      intros: { theme: 'Ikuti tema', door: 'Pintu', curtain: 'Tirai', envelope: 'Amplop', zoom: 'Zoom', bloom: 'Bunga mekar', blossom: 'Bunga berputar', gunungan: 'Gunungan', iris: 'Iris', split: 'Belah layar', slide: 'Geser', flip: 'Balik 3D', cube: 'Kubus 3D' },
      levels: {
        full: { label: 'Penuh', hint: 'Semua animasi' },
        light: { label: 'Ringan', hint: 'Tanpa ornamen' },
        off: { label: 'Mati', hint: 'Tanpa animasi' },
      },
      introTitle: 'Animasi pembuka',
      introAria: 'Animasi pembuka',
      introNote: 'Pembuka khusus hanya aktif pada tingkat animasi “Penuh”.',
      levelTitle: 'Tingkat animasi',
      levelAria: 'Tingkat animasi',
      levelNote: '“Ringan” cocok untuk HP dengan spesifikasi rendah. Pengunjung yang mematikan animasi di perangkatnya otomatis tidak melihat gerakan.',
      fontHeadingAria: 'Font judul',
      fontBodyAria: 'Font isi',
      sizeAria: 'Ukuran judul',
      orderReset: 'Urutan awal',
      orderHint: 'Seret ikon pegangan (juga di layar sentuh), atau pakai tombol panah. Matikan saklar untuk menyembunyikan bagian.',
      showSection: 'Tampilkan',
      moveUp: 'Naikkan',
      moveDown: 'Turunkan',
      movedTo: 'dipindah ke urutan',
      movedOf: 'dari',
      sampleCouple: 'Raka & Sinta',
      sampleMuted: 'Dengan memohon rahmat dan ridho Allah SWT…',
      sampleEvent: 'Akad Nikah',
      sampleVenue: 'Gedung Graha Bakti',
      sampleOpen: 'Buka Undangan',
    },
    share: {
      desc: 'Buat tautan khusus untuk setiap tamu dan kirim lewat WhatsApp. Nama tamu muncul di cover undangan.',
      defaultTemplate: 'Kepada Yth. {nama},\n\nDengan penuh kebahagiaan kami mengundang Anda ke pernikahan {pasangan}.\nBuka undangan digital kami di:\n{link}\n\nTerima kasih atas doa dan restunya.',
      notPublished: 'Tautan baru bisa dibuka tamu setelah undangan dipublikasikan.',
      needSlug: 'Isi alamat undangan (slug) di bagian Info dasar terlebih dahulu.',
      qrAlt: 'Kode QR tautan undangan',
      generalLink: 'Tautan umum',
      copyLink: 'Salin',
      downloadQr: 'Unduh QR',
      guestList: 'Daftar tamu',
      guestHint: 'Satu nama per baris. Tambahkan nomor WhatsApp setelah tanda | agar pesan langsung terbuka ke kontak itu, mis. Budi Santoso | 0812xxxx',
      guestPh: 'Budi Santoso | 081234567890\nKeluarga Bapak Andi',
      waMessage: 'Pesan WhatsApp',
      waHint: 'Gunakan {nama}, {pasangan}, dan {link}.',
      resetTemplate: 'Kembalikan pesan awal',
      guestUnit: 'tamu',
      copyAll: 'Salin semua tautan',
      copyAllDone: 'tautan disalin (nama ⇥ tautan, siap tempel ke spreadsheet)',
      emptyGuests: 'Tambahkan nama tamu untuk membuat tautan pribadi.',
      copyLinkOf: 'Salin tautan',
      sendViaWa: 'lewat WhatsApp',
      send: 'Kirim',
      sendTo: 'Kirim ke',
    },
    seo: {
      desc: 'Judul dan deskripsi saat tautan dibagikan di WhatsApp atau mesin pencari.',
      coupleFallback: 'Nama Pasangan',
      title: 'Judul halaman',
      titleHint: 'Kosongkan untuk memakai: ',
      descLabel: 'Deskripsi',
      descHint: 'Kosongkan untuk memakai: ',
      hideSeo: 'Sembunyikan dari mesin pencari',
      hideHint: 'Disarankan untuk undangan pribadi. Tautan tetap bisa dibuka siapa saja yang memilikinya.',
      portfolio: 'Tampilkan di portofolio',
      portfolioHint: 'Muncul di halaman Portofolio company profile setelah dipublikasikan. Pastikan pelanggan setuju.',
      previewTitle: 'Pratinjau hasil pencarian',
    },
    publish: {
      desc: 'Periksa kelengkapan, lalu publikasikan agar tautan bisa dibuka tamu.',
      publishedAt: 'Terbit sejak',
      draftNote: 'Hanya Anda yang bisa melihat undangan ini.',
      checklist: 'Kelengkapan',
      allGood: 'Semua data penting sudah lengkap.',
      linkTitle: 'Tautan undangan',
      stillCanPublish: 'Anda tetap bisa mempublikasikan.',
      guestParamNote: 'Tautan baru bisa dibuka tamu setelah undangan dipublikasikan. Tambahkan',
      guestParamNote2: 'untuk menyapa tamu dengan nama.',
    },
    music: {
      desc: 'Musik mulai setelah tamu menekan Buka Undangan.',
      enable: 'Aktifkan musik latar',
      url: 'Tautan audio',
      urlHint: 'Tautan langsung ke file MP3/OGG. Gunakan tautan https://…',
      urlInvalid: 'Gunakan tautan https:// langsung ke file audio.',
      badUrl: 'Audio tidak dapat diputar dari tautan ini. Pakai tautan langsung (bukan halaman YouTube/Spotify).',
    },
    publishedToast: 'Undangan dipublikasikan',
    unpublishedToast: 'Publikasi dibatalkan',
    savedToast: 'Perubahan disimpan',
    linkCopied: 'Tautan undangan disalin',
    stylePreview: 'Pratinjau gaya',
    styleText: 'Teks',
    styleTextColor: 'Warna teks utama',
    styleMutedColor: 'Warna teks sekunder',
    styleHeadingFont: 'Font judul',
    styleBodyFont: 'Font isi',
    styleHeadingSize: 'Ukuran judul bagian',
    styleSizeS: 'Kecil',
    styleSizeM: 'Sedang',
    styleSizeL: 'Besar',
    styleAccent: 'Warna aksen',
    styleSurface: 'Latar kartu',
    styleSurfaceColor: 'Warna latar kartu',
    styleAnimation: 'Animasi & pembuka',
    styleOrder: 'Bagian & urutan',
    followTheme: 'Ikuti tema',
    customColor: 'Warna khusus',
    lowContrast: 'Warna ini terlalu mirip dengan latar, teks bisa sulit dibaca.',
    themeResetToast: 'Warna khusus dikembalikan mengikuti tema baru. Tekan Urungkan untuk membatalkan.',
  },
  empty: {
    invitations: 'Belum ada undangan. Buat undangan pertama untuk pelanggan Anda.',
    customers: 'Belum ada pelanggan. Tambahkan pelanggan untuk mulai membuat undangan.',
    events: 'Belum ada acara. Tambahkan Akad Nikah atau Resepsi.',
    stories: 'Belum ada kisah. Ceritakan awal pertemuan, lamaran, hingga hari pernikahan.',
    gallery: 'Belum ada foto. Unggah foto prewedding untuk galeri.',
    gifts: 'Belum ada rekening atau e-wallet.',
    orders: 'Belum ada pesanan. Catat pesanan pertama dari pelanggan Anda.',
    rsvps: 'Belum ada konfirmasi kehadiran.',
    messages: 'Belum ada ucapan dari tamu.',
    giftConfirmations: 'Belum ada konfirmasi hadiah.',
  },
  orders: {
    title: 'Pesanan',
    add: 'Tambah pesanan',
    create: 'Buat pesanan',
    edit: 'Edit pesanan',
    customer: 'Pelanggan',
    invitation: 'Undangan',
    noInvitation: 'Tanpa undangan',
    tier: 'Paket',
    tiers: { basic: 'Basic', premium: 'Premium', luxury: 'Luxury' },
    theme: 'Tema',
    selectTheme: 'Pilih tema…',
    themeTierHint: 'Hanya tema paket',
    themeResetToTier: 'Tema disesuaikan ke paket yang dipilih.',
    themeNotInTier: 'Tema tidak termasuk dalam paket ini.',
    amountFromTier: 'Otomatis dari harga paket saat dibuat',
    customAmount: 'Harga khusus (beda dari harga paket)',
    syncToTier: 'Samakan',
    amount: 'Total harga (Rp)',
    paid: 'Terbayar (Rp)',
    paidLabel: 'Terbayar',
    remaining: 'Sisa',
    status: 'Status bayar',
    dueDate: 'Tenggat',
    notes: 'Catatan',
    statuses: { pending: 'Menunggu', dp: 'DP', paid: 'Lunas', cancelled: 'Batal' },
    saved: 'Pesanan disimpan',
    deleted: 'Pesanan dihapus',
    deleteTitle: 'Hapus pesanan?',
    deleteMessage: 'Pesanan ini akan dihapus permanen. Undangan dan pelanggan tidak ikut terhapus.',
    steps: ['Pesanan', 'Undangan', 'Publish', 'Serah terima'],
    makeInvitation: 'Buat undangan',
    invitationTitle: 'Judul undangan',
    openBuilder: 'Buka builder',
    viewAnalytics: 'Analitik',
    infoTheme: 'Tema & paket',
    infoLink: 'Tautan publik',
    infoPublished: 'Tanggal publish',
    infoWeddingDay: 'Hari-H',
    infoEvents: 'Acara',
    infoEventsUnit: 'acara',
    infoUnnamedEvent: 'Acara',
    infoGuests: 'Tamu',
    infoAttending: 'hadir',
    infoGuestsUnit: 'tamu',
    infoMessages: 'Ucapan',
    infoGifts: 'Hadiah',
    infoAmount: 'Nilai pesanan',
    infoTierNow: 'harga paket kini',
    markDelivered: 'Tandai link terkirim',
    delivered: 'Link sudah dikirim ke pelanggan',
    payments: 'Riwayat pembayaran',
    recordPayment: 'Catat pembayaran',
    paymentAmount: 'Nominal (Rp)',
    paymentMethod: 'Metode',
    paymentDate: 'Tanggal bayar',
    paymentNote: 'Catatan',
    paymentSaved: 'Pembayaran dicatat',
    paymentDeleted: 'Pembayaran dihapus',
    methods: { transfer: 'Transfer bank', ewallet: 'E-wallet', cash: 'Tunai', other: 'Lainnya' },
    unpaidWarning: 'Pesanan belum lunas. Sisa pembayaran:',
    overdue: 'Lewat tenggat',
    receivable: 'Piutang',
    activeOrders: 'Pesanan aktif',
    newOrder: 'Pesanan baru',
    selectCustomer: 'Pilih pelanggan',
    searchPh: 'Cari pelanggan, undangan, atau catatan',
    searchAria: 'Cari pesanan',
    filterAria: 'Filter status',
    noMatch: 'Tidak ada pesanan yang cocok.',
    detail: 'Detail',
    remainingOf: 'Sisa',
    makeFailed: 'Pilih pelanggan terlebih dahulu.',
    subtitle: 'Pesanan = transaksi (pembayaran), Undangan = hasil digitalnya (tautan)',
    deleteAria: 'Hapus pesanan',
    countUnit: 'pesanan',
    createdGoBuilder: 'Undangan dibuat, silakan lengkapi di builder',
    editOrder: 'Edit pesanan',
    noInvitationYet: 'Undangan digital belum dibuat untuk pesanan ini.',
    invitationIs: 'Undangan:',
    publishedShort: 'Terbit',
    draftShort: 'Draf',
    notDelivered: 'Belum dikirim',
    handoverAsk: 'Tautan undangan sudah dikirim ke pelanggan?',
    noPayments: 'Belum ada pembayaran tercatat.',
    accessCode: 'Kode akses pelanggan',
    accessCodeHint: 'Kode reusable: pasangan masuk dengan kode + email kapan pun. Kode tersimpan di sini bila lupa.',
    codeReusable: 'Kode reusable — tidak hangus setelah dipakai.',
    codeLastUsed: 'Terakhir dipakai',
    makeAccessCode: 'Buat kode akses',
    copyCode: 'Salin kode',
    codeCopied: 'Kode berhasil disalin',
    codeDeactivated: 'Kode dinonaktifkan',
    deactivateCode: 'Nonaktifkan kode',
    existingCode: 'Kode aktif untuk pesanan ini:',
    needPaidFirst: 'Pesanan harus lunas dulu sebelum kode akses dibuat.',
    needInvitationFirst: 'Buatkan dulu 1 undangan untuk pesanan ini sebelum membuat kode akses.',
    deletePayment: 'Hapus pembayaran',
    deletePaymentTitle: 'Hapus pembayaran?',
    deletePaymentMsg: 'Total terbayar akan dikurangi sejumlah nominal ini.',
    payNotePh: 'DP / pelunasan',
  },
  themes: {
    title: 'Tema',
    subtitle: 'Tema dikelompokkan per paket. Harga diatur per paket dan berlaku sama untuk semua tema di dalamnya.',
    tierPrice: 'Harga paket',
    tierPriceHint: 'Berlaku untuk pesanan baru, tidak mengubah pesanan lama',
    noTierPrice: 'Belum diatur',
    activeCount: 'aktif',
    price: 'Harga (Rp)',
    active: 'Tampil',
    saved: 'Tema disimpan',
    empty: 'Katalog tema belum tersedia.',
    category: 'Kategori',
    tier: 'Paket',
    locked: 'Di luar paket Anda',
    upgradeHint: 'Hubungi admin untuk upgrade paket.',
    saving: 'Menyimpan…',
  },
  rsvpAdmin: {
    title: 'RSVP',
    attending: 'Hadir',
    notAttending: 'Tidak hadir',
    guests: 'tamu',
    search: 'Cari nama atau pesan',
    searchAria: 'Cari RSVP',
    filterAria: 'Filter kehadiran',
    sortAria: 'Urutkan',
    newest: 'Terbaru',
    nameAz: 'Nama A–Z',
    noMatch: 'Tidak ada yang cocok.',
    csvHeaders: ['Nama', 'WhatsApp', 'Kehadiran', 'Jumlah', 'Pesan', 'Waktu'],
    csvFallback: 'undangan',
  },
  messagesAdmin: {
    title: 'Ucapan',
    hide: 'Sembunyikan',
    show: 'Tampilkan',
    hidden: 'Disembunyikan',
    deleteTitle: 'Hapus ucapan?',
    deleteMsg: 'Ucapan ini akan dihapus permanen.',
    searchPh: 'Cari nama atau ucapan',
    searchAria: 'Cari ucapan',
    noMatch: 'Tidak ada yang cocok.',
  },
  giftsAdmin: {
    title: 'Hadiah',
    confirmations: 'Konfirmasi masuk',
    accounts: 'Rekening & e-wallet',
    total: 'Total terkonfirmasi',
    types: { bank_transfer: 'Transfer bank', e_wallet: 'E-wallet', cash: 'Tunai', other: 'Lainnya' },
    kinds: { bank: 'Transfer Bank', e_wallet: 'E-Wallet' },
    holderPrefix: 'a.n.',
  },
  settings: {
    tabs: { content: 'Konten situs', testimonials: 'Testimoni', faqs: 'FAQ' },
    tabAria: 'Pengaturan',
    heroTitle: 'Judul hero beranda',
    heroSubtitle: 'Subjudul hero beranda',
    seoTitle: 'Judul SEO beranda',
    seoDescription: 'Deskripsi SEO beranda',
    contactText: 'Teks halaman kontak',
    savedContent: 'Konten situs disimpan',
    addTestimonial: 'Tambah testimoni',
    noTestimonials: 'Belum ada testimoni.',
    testimonialModal: 'Testimoni',
    tName: 'Nama',
    tMessage: 'Isi testimoni',
    tRating: 'Rating (1–5)',
    tPosition: 'Urutan',
    tVisible: 'Tampilkan di situs',
    savedTestimonial: 'Testimoni disimpan',
    addFaq: 'Tambah FAQ',
    noFaqs: 'Belum ada FAQ.',
    faqModal: 'FAQ',
    fQuestion: 'Pertanyaan',
    fAnswer: 'Jawaban',
    fPosition: 'Urutan',
    fVisible: 'Tampilkan di situs',
    savedFaq: 'FAQ disimpan',
    deleted: 'Dihapus',
    editFaq: 'Edit FAQ',
    deleteFaq: 'Hapus FAQ',
    deleteTitle: 'Hapus?',
    deleteMsg: 'Data ini akan dihapus permanen dari situs.',
  },
  couple: {
    portalBadge: 'Portal Pasangan',
    loginTitle: 'Masuk dengan kode akses',
    loginSubtitle: 'Sudah pernah masuk? Pakai email yang sama, kami kirimkan tautan masuk.',
    magicLinkTitle: 'Masuk via tautan email',
    sendLink: 'Kirim tautan masuk',
    linkSentTitle: 'Tautan terkirim',
    linkSentMessage: 'Buka email Anda dan klik tautannya. Tautan hanya berlaku singkat.',
    dashboardTitle: 'Pantauan Undangan',
    dashboardSubtitle: 'Kehadiran tamu, ucapan, dan hadiah — diperbarui otomatis.',
    navDashboard: 'Dashboard',
    navDetail: 'Undangan saya',
    navManage: 'Edit undangan',
    menuAria: 'Menu pasangan',
    statusLabel: 'Status',
    updatedAt: 'Diperbarui',
    backToDashboard: 'Kembali ke dashboard',
    noInvitations: 'Belum ada undangan untuk akun ini. Hubungi admin via WhatsApp.',
    invitationUnit: 'Undangan',
    publishedShort: 'Terbit',
    draftShort: 'Draf',
    pendingResponse: 'Belum respons',
    detailLink: 'Tautan undangan',
    revisionCta: 'Minta revisi',
    revisionMsg: 'Halo {company}, saya ingin minta revisi undangan {couple} ({link}). Detailnya: ',
    dataFresh: 'Data diperbarui otomatis setiap Anda membuka halaman ini.',
    hasCode: 'Punya kode akses?',
    redeemTitle: 'Tukar kode akses',
    redeemSubtitle: 'Masukkan kode dari admin (contoh TJ-AB12-CD34) dan email Anda.',
    noCodeHint: 'Belum punya kode? Minta ke admin via WhatsApp setelah pelunasan.',
    codeLabel: 'Kode akses',
    codePh: 'TJ-XXXX-XXXX',
    redeemCta: 'Tukar & masuk',
    anonDisabled: 'Login kode butuh Anonymous sign-ins aktif di Supabase (Authentication → Providers → Anonymous). Minta admin mengaktifkannya, atau masuk via tautan email di bawah.',
    createTitle: 'Buat undangan baru',
    createCta: 'Buat undangan',
    createNamePh: 'Nama undangan (mis. Budi & Ayu)',
    manageCta: 'Kelola',
    needPaidOrder: 'Pesanan perlu dilunasi admin dulu sebelum undangan bisa dibuat.',
    quotaUsed: 'Undangan untuk pesanan ini sudah dibuat.',
    quotaReady: 'Siap dibuat — 1 pesanan untuk 1 undangan.',
    singleReady: 'Undangan Anda sudah disiapkan admin. Silakan kelola dan publikasikan.',
    waitingAdmin: 'Undangan Anda sedang disiapkan admin. Hubungi admin via WhatsApp jika belum muncul.',
    themeOutside: 'Tema tidak termasuk dalam paket Anda. Hubungi admin untuk upgrade.',
    savedToast: 'Perubahan disimpan',
  },
  site: {
    homeTitle: 'Undangan Pernikahan Digital Elegan — Talijiwa',
    homeDescription: 'Buat undangan pernikahan digital yang indah, interaktif, dan mudah dibagikan lewat WhatsApp.',
    templatesTitle: 'Template Undangan Pernikahan Digital',
    templatesDescription: 'Pilih tampilan undangan pernikahan digital: klasik, modern, floral, adat, dan mewah, lengkap dengan harga transparan.',
    portfolioTitle: 'Portofolio Undangan Pernikahan',
    portfolioDescription: 'Contoh undangan pernikahan digital yang telah kami buat untuk para pelanggan.',
    servicesTitle: 'Layanan & Harga Undangan Pernikahan Digital',
    servicesDescription: 'Paket undangan pernikahan digital: template siap pakai, RSVP, amplop digital, dan QR tamu. Harga transparan.',
    aboutTitle: 'Tentang Kami — Vendor Undangan Pernikahan Digital',
    aboutDescription: 'Talijiwa membantu pasangan menyebar undangan pernikahan digital yang elegan, interaktif, dan mudah dipantau.',
    contactTitle: 'Kontak — Pesan Undangan Pernikahan Digital',
    testimonialsTitle: 'Kata mereka',
    faqTitle: 'Pertanyaan umum',
  },
  company: {
    badge: 'Undangan Pernikahan Digital',
    viewTemplates: 'Lihat Template',
    orderNow: 'Pesan Sekarang',
    coupleLogin: 'Masuk Pasangan',
    stats: [
      { value: '11+', label: 'Pilihan tema elegan' },
      { value: '1–3', label: 'Hari pengerjaan' },
      { value: '24/7', label: 'Undangan selalu online' },
    ],
    featuresTitle: 'Kenapa Talijiwa?',
    featuresSubtitle: 'Semua yang Anda butuhkan untuk undangan yang berkesan, tanpa ribet.',
    features: [
      { slot: 'featureDesign', title: 'Desain dikerjakan untuk Anda', desc: 'Ceritakan gaya impian Anda, tim kami yang menuangkannya menjadi undangan cantik dalam 1–3 hari.' },
      { slot: 'featureRsvp', title: 'RSVP & ucapan otomatis', desc: 'Tamu konfirmasi kehadiran dan menitipkan doa langsung dari undangannya. Tanpa buku tamu kertas.' },
      { slot: 'featureShare', title: 'Siap kirim via WhatsApp', desc: 'Terima tautan, kode QR, dan pesan siap kirim untuk setiap tamu. Satu klik langsung terkirim.' },
    ],
    stepsTitle: 'Cara pesan',
    steps: [
      'Chat WhatsApp dan pilih template favorit Anda.',
      'Kirim data + foto, kami garap 1–3 hari kerja.',
      'Terima tautan + QR + pesan siap kirim ke tamu.',
      'Pantau kehadiran tamu real-time dari dashboard pasangan.',
    ],
    featuredTitle: 'Template favorit',
    viewAll: 'Lihat semua template',
    finalTitle: 'Siap membuat undangan yang berkesan?',
    finalSubtitle: 'Ceritakan tanggal dan impian pernikahan Anda, kami bantu wujudkan undangannya.',
    templatesHeading: 'Template',
    templatesSubtitle: 'Pilih tampilan yang paling sesuai dengan suasana pernikahan Anda.',
    allCategories: 'Semua',
    viewDemo: 'Lihat Demo',
    viewSample: 'Lihat contoh',
    noTemplates: 'Belum ada template pada kategori ini.',
    portfolioHeading: 'Portofolio',
    portfolioSubtitle: 'Karya undangan yang telah kami buat dengan penuh cinta.',
    viewInvitation: 'Lihat Undangan',
    portfolioEmpty: 'Portofolio segera hadir. Jadilah yang pertama — pesan undangan Anda hari ini.',
    servicesHeading: 'Layanan & Harga',
    servicesSubtitle: 'Satu harga per template, sudah termasuk semua fitur. Tanpa biaya tersembunyi.',
    tiersTitle: 'Pilih paket Anda',
    tierPopular: 'Paling laris',
    tierCustomCta: 'Tanya custom',
    tiers: [
      { name: 'Semua Tema', desc: 'Harga termurah dari seluruh katalog, semua fitur included.', features: ['Semua fitur RSVP, ucapan & amplop digital', 'Tautan + kode QR siap kirim', 'Revisi ringan selama pengerjaan', 'Aktif selamanya, tanpa perpanjangan'] },
      { name: 'Adat & Mewah', desc: 'Motif batik, emas, dan ornamen premium untuk hari istimewa.', features: ['Semua fitur paket Semua Tema', 'Konsultasi motif & warna khusus', 'Prioritas pengerjaan', 'Cover animasi pembuka premium'] },
      { name: 'Custom Penuh', desc: 'Punya referensi sendiri? Kami wujudkan dari nol.', features: ['Desain 100% sesuai referensi Anda', 'Revisi sampai cocok', 'Konsultasi langsung via WhatsApp', 'Harga menyesuaikan kerumitan'] },
    ],
    aboutHeading: 'Tentang Kami',
    aboutStory: [
      'Talijiwa lahir dari keyakinan sederhana: undangan adalah kesan pertama sebuah pernikahan. Kami membantu pasangan menyebarkan kabar bahagia lewat undangan digital yang elegan, interaktif, dan mudah dibagikan.',
      'Setiap pasangan mendapat dashboard pantauan: siapa yang hadir, siapa yang berhalangan, ucapan yang masuk, dan konfirmasi hadiah — diperbarui otomatis tanpa perlu bertanya.',
      'Kami berbasis di Surakarta, Jawa Tengah, dan melayani seluruh Indonesia.',
    ],
    valuesTitle: 'Yang kami pegang',
    values: [
      { title: 'Personal', desc: 'Setiap undangan digarap manusia, bukan template sekali-klik. Gaya Anda, sentuhan kami.' },
      { title: 'Cepat & rapi', desc: 'Jadi dalam 1–3 hari kerja, rapi di semua ukuran layar HP tamu Anda.' },
      { title: 'Privasi terjaga', desc: 'Data tamu dan momen Anda tidak disebar. Tautan hanya untuk yang Anda undang.' },
    ],
    contactHeading: 'Kontak',
    contactHours: 'Setiap hari, 09.00–21.00 WIB',
    chatWhatsapp: 'Chat via WhatsApp',
    contactLabels: { whatsapp: 'WhatsApp', email: 'Email', instagram: 'Instagram', address: 'Alamat', hours: 'Jam layanan' },
    priceFrom: 'Mulai',
    priceAsk: 'Tanya harga',
    chooseTier: 'Pilih',
    tierInterest: 'Halo, saya tertarik dengan {name}.',
    notFoundTitle: 'Halaman tidak ditemukan',
    notFoundSubtitle: 'Alamat yang Anda buka tidak tersedia.',
    backHome: 'Kembali ke beranda',
  },
} as const

/** Labels for the "bagian yang ditampilkan" toggles in the builder (keys = SectionKey). */
export const sectionLabels = {
  couple: { label: 'Sambutan & nama mempelai', hint: 'Salam pembuka dan teks pembuka.' },
  date: { label: 'Tanggal pernikahan', hint: 'Diambil dari acara paling awal.' },
  countdown: { label: 'Hitung mundur', hint: 'Menuju waktu mulai acara pertama.' },
  profile: { label: 'Profil mempelai', hint: 'Foto, nama, dan orang tua.' },
  story: { label: 'Kisah cinta', hint: 'Timeline perjalanan pasangan.' },
  events: { label: 'Rangkaian acara', hint: 'Akad, resepsi, dan acara lain.' },
  maps: { label: 'Tombol peta', hint: 'Muncul jika acara punya tautan peta.' },
  gallery: { label: 'Galeri foto', hint: 'Grid foto dengan lightbox.' },
  rsvp: { label: 'Konfirmasi kehadiran', hint: 'Form RSVP untuk tamu.' },
  messages: { label: 'Ucapan & doa', hint: 'Form dan daftar ucapan tamu.' },
  gift: { label: 'Amplop digital', hint: 'Rekening, e-wallet, dan konfirmasi hadiah.' },
} as const
