/**
 * All user-facing text (Indonesian). Keep strings here, never inside components.
 * Grouped by area so a future i18n layer can replace this file.
 */
export const copy = {
  common: {
    save: 'Simpan',
    saving: 'Menyimpan…',
    saved: 'Tersimpan',
    unsaved: 'Belum disimpan',
    cancel: 'Batal',
    delete: 'Hapus',
    edit: 'Edit',
    add: 'Tambah',
    search: 'Cari',
    loading: 'Memuat…',
    back: 'Kembali',
    copyLink: 'Salin tautan',
    copied: 'Berhasil disalin',
    preview: 'Pratinjau',
    publish: 'Publikasikan',
    unpublish: 'Batalkan publikasi',
    genericError: 'Terjadi kesalahan. Silakan coba lagi.',
    optional: 'opsional',
  },
  auth: {
    title: 'Masuk ke panel admin',
    subtitle: 'Kelola pelanggan dan undangan Anda.',
    email: 'Email',
    password: 'Kata sandi',
    submit: 'Masuk',
    invalid: 'Email atau kata sandi salah.',
    notAdmin: 'Akun ini tidak memiliki akses admin.',
    logout: 'Keluar',
    mockHint: 'Mode demo: gunakan admin@talijiwa.id / admin123',
  },
  nav: {
    dashboard: 'Dashboard',
    customers: 'Pelanggan',
    orders: 'Pesanan',
    invitations: 'Undangan',
    themes: 'Tema',
    analytics: 'Analitik',
    settings: 'Pengaturan',
  },
  invitation: {
    notFound: 'Undangan tidak ditemukan',
    notPublished: 'Undangan belum dipublikasikan',
    unavailable: 'Undangan ini sudah tidak tersedia',
    weddingOf: 'THE WEDDING OF',
    dear: 'Kepada Yth.',
    defaultGuest: 'Bapak/Ibu/Saudara/i',
    open: 'Buka Undangan',
    todayIsTheDay: 'Hari Bahagia Telah Tiba',
    days: 'Hari',
    hours: 'Jam',
    minutes: 'Menit',
    seconds: 'Detik',
    copyNumber: 'Salin Nomor',
    copied: 'Berhasil disalin',
    openMaps: 'Buka Peta',
  },
  builder: {
    sections: {
      basic: 'Info dasar',
      couple: 'Mempelai',
      story: 'Kisah cinta',
      events: 'Acara',
      gallery: 'Galeri',
      rsvp: 'RSVP',
      messages: 'Ucapan',
      gift: 'Amplop digital',
      music: 'Musik',
      theme: 'Tema & gaya',
      seo: 'SEO',
      publish: 'Publikasi',
      share: 'Bagikan',
    },
    unsavedWarning: 'Perubahan belum disimpan. Yakin ingin meninggalkan halaman ini?',
    tabEdit: 'Edit',
    tabPreview: 'Pratinjau',
    publishedToast: 'Undangan dipublikasikan',
    unpublishedToast: 'Publikasi dibatalkan',
    savedToast: 'Perubahan disimpan',
    linkCopied: 'Tautan undangan disalin',
    stylePreview: 'Pratinjau gaya',
    styleText: 'Teks',
    styleTextColor: 'Warna teks utama',
    styleMutedColor: 'Warna teks sekunder',
    styleHeadingFont: 'Font judul',
    styleBodyFont: 'Font isi',
    styleHeadingSize: 'Ukuran judul bagian',
    styleSizeS: 'Kecil',
    styleSizeM: 'Sedang',
    styleSizeL: 'Besar',
    styleAccent: 'Warna aksen',
    styleSurface: 'Latar kartu',
    styleSurfaceColor: 'Warna latar kartu',
    styleAnimation: 'Animasi & pembuka',
    styleOrder: 'Bagian & urutan',
    followTheme: 'Ikuti tema',
    customColor: 'Warna khusus',
    lowContrast: 'Warna ini terlalu mirip dengan latar, teks bisa sulit dibaca.',
    themeResetToast: 'Warna khusus dikembalikan mengikuti tema baru. Tekan Urungkan untuk membatalkan.',
  },
  empty: {
    invitations: 'Belum ada undangan. Buat undangan pertama untuk pelanggan Anda.',
    customers: 'Belum ada pelanggan. Tambahkan pelanggan untuk mulai membuat undangan.',
    events: 'Belum ada acara. Tambahkan Akad Nikah atau Resepsi.',
    stories: 'Belum ada kisah. Ceritakan awal pertemuan, lamaran, hingga hari pernikahan.',
    gallery: 'Belum ada foto. Unggah foto prewedding untuk galeri.',
    gifts: 'Belum ada rekening atau e-wallet.',
    orders: 'Belum ada pesanan. Catat pesanan pertama dari pelanggan Anda.',
    rsvps: 'Belum ada konfirmasi kehadiran.',
    messages: 'Belum ada ucapan dari tamu.',
    giftConfirmations: 'Belum ada konfirmasi hadiah.',
  },
  orders: {
    title: 'Pesanan',
    add: 'Tambah pesanan',
    edit: 'Edit pesanan',
    customer: 'Pelanggan',
    invitation: 'Undangan',
    noInvitation: 'Tanpa undangan',
    theme: 'Tema',
    amount: 'Total harga (Rp)',
    paid: 'Terbayar (Rp)',
    remaining: 'Sisa',
    status: 'Status bayar',
    dueDate: 'Tenggat',
    notes: 'Catatan',
    statuses: { pending: 'Menunggu', dp: 'DP', paid: 'Lunas', cancelled: 'Batal' },
    saved: 'Pesanan disimpan',
    deleted: 'Pesanan dihapus',
    deleteTitle: 'Hapus pesanan?',
    deleteMessage: 'Pesanan ini akan dihapus permanen. Undangan dan pelanggan tidak ikut terhapus.',
    steps: ['Pesanan', 'Undangan', 'Publish', 'Serah terima'],
    makeInvitation: 'Buat undangan',
    openBuilder: 'Buka builder',
    markDelivered: 'Tandai link terkirim',
    delivered: 'Link sudah dikirim ke pelanggan',
    payments: 'Riwayat pembayaran',
    recordPayment: 'Catat pembayaran',
    paymentAmount: 'Nominal (Rp)',
    paymentMethod: 'Metode',
    paymentDate: 'Tanggal bayar',
    paymentNote: 'Catatan',
    paymentSaved: 'Pembayaran dicatat',
    paymentDeleted: 'Pembayaran dihapus',
    methods: { transfer: 'Transfer bank', ewallet: 'E-wallet', cash: 'Tunai', other: 'Lainnya' },
    unpaidWarning: 'Pesanan belum lunas. Sisa pembayaran:',
    overdue: 'Lewat tenggat',
    receivable: 'Piutang',
    activeOrders: 'Pesanan aktif',
    newOrder: 'Pesanan baru',
  },
  themes: {
    title: 'Tema',
    subtitle: 'Atur tema yang tampil di halaman Template dan harganya. Desain tema tetap dari kode.',
    price: 'Harga (Rp)',
    active: 'Tampil',
    saved: 'Tema disimpan',
  },
  rsvpAdmin: {
    title: 'RSVP',
    attending: 'Hadir',
    notAttending: 'Tidak hadir',
    guests: 'tamu',
    search: 'Cari nama atau pesan',
  },
  messagesAdmin: {
    title: 'Ucapan',
    hide: 'Sembunyikan',
    show: 'Tampilkan',
    hidden: 'Disembunyikan',
  },
  giftsAdmin: {
    title: 'Hadiah',
    confirmations: 'Konfirmasi masuk',
    accounts: 'Rekening & e-wallet',
    total: 'Total terkonfirmasi',
  },
  couple: {
    loginTitle: 'Pantau undangan Anda',
    loginSubtitle: 'Masukkan email yang terdaftar, kami kirimkan tautan masuk.',
    sendLink: 'Kirim tautan masuk',
    linkSentTitle: 'Tautan terkirim',
    linkSentMessage: 'Buka email Anda dan klik tautannya. Tautan hanya berlaku singkat.',
    dashboardTitle: 'Pantauan Undangan',
    dashboardSubtitle: 'Kehadiran tamu, ucapan, dan hadiah — diperbarui otomatis.',
    noInvitations: 'Belum ada undangan untuk akun ini. Hubungi admin via WhatsApp.',
  },
  site: {
    homeTitle: 'Undangan Pernikahan Digital Elegan — Talijiwa',
    homeDescription: 'Buat undangan pernikahan digital yang indah, interaktif, dan mudah dibagikan lewat WhatsApp.',
    templatesTitle: 'Template Undangan Pernikahan Digital',
    templatesDescription: 'Pilih tampilan undangan pernikahan digital: klasik, modern, floral, adat, dan mewah, lengkap dengan harga transparan.',
    portfolioTitle: 'Portofolio Undangan Pernikahan',
    portfolioDescription: 'Contoh undangan pernikahan digital yang telah kami buat untuk para pelanggan.',
    servicesTitle: 'Layanan & Harga Undangan Pernikahan Digital',
    servicesDescription: 'Paket undangan pernikahan digital: template siap pakai, RSVP, amplop digital, dan QR tamu. Harga transparan.',
    aboutTitle: 'Tentang Kami — Vendor Undangan Pernikahan Digital',
    aboutDescription: 'Talijiwa membantu pasangan menyebar undangan pernikahan digital yang elegan, interaktif, dan mudah dipantau.',
    contactTitle: 'Kontak — Pesan Undangan Pernikahan Digital',
    testimonialsTitle: 'Kata mereka',
    faqTitle: 'Pertanyaan umum',
  },
  company: {
    badge: 'Undangan Pernikahan Digital',
    viewTemplates: 'Lihat Template',
    orderNow: 'Pesan Sekarang',
    stats: [
      { value: '11+', label: 'Pilihan tema elegan' },
      { value: '1–3', label: 'Hari pengerjaan' },
      { value: '24/7', label: 'Undangan selalu online' },
    ],
    featuresTitle: 'Kenapa Talijiwa?',
    featuresSubtitle: 'Semua yang Anda butuhkan untuk undangan yang berkesan, tanpa ribet.',
    features: [
      { slot: 'featureDesign', title: 'Desain dikerjakan untuk Anda', desc: 'Ceritakan gaya impian Anda, tim kami yang menuangkannya menjadi undangan cantik dalam 1–3 hari.' },
      { slot: 'featureRsvp', title: 'RSVP & ucapan otomatis', desc: 'Tamu konfirmasi kehadiran dan menitipkan doa langsung dari undangannya. Tanpa buku tamu kertas.' },
      { slot: 'featureShare', title: 'Siap kirim via WhatsApp', desc: 'Terima tautan, kode QR, dan pesan siap kirim untuk setiap tamu. Satu klik langsung terkirim.' },
    ],
    stepsTitle: 'Cara pesan',
    steps: [
      'Chat WhatsApp dan pilih template favorit Anda.',
      'Kirim data + foto, kami garap 1–3 hari kerja.',
      'Terima tautan + QR + pesan siap kirim ke tamu.',
      'Pantau kehadiran tamu real-time dari dashboard pasangan.',
    ],
    featuredTitle: 'Template favorit',
    viewAll: 'Lihat semua template',
    finalTitle: 'Siap membuat undangan yang berkesan?',
    finalSubtitle: 'Ceritakan tanggal dan impian pernikahan Anda, kami bantu wujudkan undangannya.',
    templatesHeading: 'Template',
    templatesSubtitle: 'Pilih tampilan yang paling sesuai dengan suasana pernikahan Anda.',
    allCategories: 'Semua',
    viewDemo: 'Lihat Demo',
    viewSample: 'Lihat contoh',
    noTemplates: 'Belum ada template pada kategori ini.',
    portfolioHeading: 'Portofolio',
    portfolioSubtitle: 'Karya undangan yang telah kami buat dengan penuh cinta.',
    viewInvitation: 'Lihat Undangan',
    portfolioEmpty: 'Portofolio segera hadir. Jadilah yang pertama — pesan undangan Anda hari ini.',
    servicesHeading: 'Layanan & Harga',
    servicesSubtitle: 'Satu harga per template, sudah termasuk semua fitur. Tanpa biaya tersembunyi.',
    tiersTitle: 'Pilih paket Anda',
    tierPopular: 'Paling laris',
    tierCustomCta: 'Tanya custom',
    tiers: [
      { name: 'Semua Tema', desc: 'Harga termurah dari seluruh katalog, semua fitur included.', features: ['Semua fitur RSVP, ucapan & amplop digital', 'Tautan + kode QR siap kirim', 'Revisi ringan selama pengerjaan', 'Aktif selamanya, tanpa perpanjangan'] },
      { name: 'Adat & Mewah', desc: 'Motif batik, emas, dan ornamen premium untuk hari istimewa.', features: ['Semua fitur paket Semua Tema', 'Konsultasi motif & warna khusus', 'Prioritas pengerjaan', 'Cover animasi pembuka premium'] },
      { name: 'Custom Penuh', desc: 'Punya referensi sendiri? Kami wujudkan dari nol.', features: ['Desain 100% sesuai referensi Anda', 'Revisi sampai cocok', 'Konsultasi langsung via WhatsApp', 'Harga menyesuaikan kerumitan'] },
    ],
    aboutHeading: 'Tentang Kami',
    aboutStory: [
      'Talijiwa lahir dari keyakinan sederhana: undangan adalah kesan pertama sebuah pernikahan. Kami membantu pasangan menyebarkan kabar bahagia lewat undangan digital yang elegan, interaktif, dan mudah dibagikan.',
      'Setiap pasangan mendapat dashboard pantauan: siapa yang hadir, siapa yang berhalangan, ucapan yang masuk, dan konfirmasi hadiah — diperbarui otomatis tanpa perlu bertanya.',
      'Kami berbasis di Surakarta, Jawa Tengah, dan melayani seluruh Indonesia.',
    ],
    valuesTitle: 'Yang kami pegang',
    values: [
      { title: 'Personal', desc: 'Setiap undangan digarap manusia, bukan template sekali-klik. Gaya Anda, sentuhan kami.' },
      { title: 'Cepat & rapi', desc: 'Jadi dalam 1–3 hari kerja, rapi di semua ukuran layar HP tamu Anda.' },
      { title: 'Privasi terjaga', desc: 'Data tamu dan momen Anda tidak disebar. Tautan hanya untuk yang Anda undang.' },
    ],
    contactHeading: 'Kontak',
    contactHours: 'Setiap hari, 09.00–21.00 WIB',
    chatWhatsapp: 'Chat via WhatsApp',
  },
} as const

/** Labels for the "bagian yang ditampilkan" toggles in the builder (keys = SectionKey). */
export const sectionLabels = {
  couple: { label: 'Sambutan & nama mempelai', hint: 'Salam pembuka dan teks pembuka.' },
  date: { label: 'Tanggal pernikahan', hint: 'Diambil dari acara paling awal.' },
  countdown: { label: 'Hitung mundur', hint: 'Menuju waktu mulai acara pertama.' },
  profile: { label: 'Profil mempelai', hint: 'Foto, nama, dan orang tua.' },
  story: { label: 'Kisah cinta', hint: 'Timeline perjalanan pasangan.' },
  events: { label: 'Rangkaian acara', hint: 'Akad, resepsi, dan acara lain.' },
  maps: { label: 'Tombol peta', hint: 'Muncul jika acara punya tautan peta.' },
  gallery: { label: 'Galeri foto', hint: 'Grid foto dengan lightbox.' },
  rsvp: { label: 'Konfirmasi kehadiran', hint: 'Form RSVP untuk tamu.' },
  messages: { label: 'Ucapan & doa', hint: 'Form dan daftar ucapan tamu.' },
  gift: { label: 'Amplop digital', hint: 'Rekening, e-wallet, dan konfirmasi hadiah.' },
} as const
